<<<<<<< HEAD
# Nombre del flujo de trabajo
name: Node.js CI

# Eventos que desencadenan la ejecución del flujo de trabajo
on:
  push:
    branches:
      - "*" # Se ejecuta cuando se hace push en cualquier rama
  pull_request:
    branches:
      - main
      - dev
=======
name: Node.js CI

on:
  push:
    branches:
      - main  # Cambia "main" al nombre de tu rama principal si es diferente
  pull_request:
    branches:
      - main  # Cambia "main" al nombre de tu rama principal si es diferente
>>>>>>> 02bec0249368a5ed116d5839173d28c0eb8bf883

# Definición del trabajo
jobs:
  build:
<<<<<<< HEAD
    runs-on: ubuntu-latest # El trabajo se ejecuta en una máquina con la última versión de Ubuntu

    # Pasos a seguir en el trabajo
    steps:
      - uses: actions/checkout@v2 # Paso para clonar el repositorio
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm ci # Instalación limpia de dependencias de Node.js
      - run: npm test # Ejecución de las pruebas del proyecto
      - run: npm run build --if-present # Construcción del código fuente si existe un script de construcción
=======
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Cambia la versión de Node.js según tus necesidades

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar tests
      run: npm run test
>>>>>>> 02bec0249368a5ed116d5839173d28c0eb8bf883
